### ISSUE TITLE
Can't play!

### ISSUE THREAD

**Issue by IwannaPlayHardCore** [MC-U-Team/U-Team-Core#11]
When launching minecraft  after I click the play button it crashes and I get this error message: The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: info.u_team.u_team_core.sub.USubMod.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V. Why do I get it? I try playing with 1.12.2

**Comment by HyCraftHD** [comment]
Can you provide me a list with all mods you are playing with that require uteamcore?
Did you update all mods (that require uteamcore) to the newest version?
If thats not helping please send me the complete logs.

**Comment by IwannaPlayHardCore** [comment]
Useful backpacka is the mod I’m playing with, and when I downloaded it I downloaded the newest version. Where can I find the full log?

**Comment by HyCraftHD** [comment]
minecraft/log/debug.log
and
.minecraft/crash-reports/crash-***-client.txt

And please check if your are really using the newest version.

**Comment by HyCraftHD** [comment]
The newest versions for usefulbackpacks is: https://minecraft.curseforge.com/projects/useful-backpacks/files/2574271
and for the lib: https://minecraft.curseforge.com/projects/u-team-core/files/2574212

**Comment by IwannaPlayHardCore** [comment]
I found the logs and the debug log is from yesterday morning, while the crash report is from the day before that.

**Comment by IwannaPlayHardCore** [comment]
I tried redownloading the files and it worked now!

**Comment by HyCraftHD** [comment]
Great ❤
Have fun
