### ISSUE TITLE
uteamcore makes game crash on startup

### ISSUE THREAD

**Issue by ajw2004** [MC-U-Team/U-Team-Core#12]
when ever i try to use uteamcore my game crashes and i get this error Error: java.lang.NoSuchMethodError: info.u_team.u_team_core.sub.USubMod.(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
how do i fix this

**Comment by HyCraftHD** [comment]
Please update all mods that require uteamcore, like usefulbackpacks to the newest version.

Duplicate of #11
