### ISSUE TITLE
Can't Change Time To Night

### ISSUE THREAD

**Issue by Seclusus** [MC-U-Team/U-Team-Core#13]
I've deleted all mods/libraries and re-added them one by one. When I load this one the game never cycles to nighttime. Please advise.

Nevermind, it was a few bugged saves.

**Comment by MrTroble** [comment]
We looked into this issue and we can't reproduce it. Keep in mind that you can change whether the daylight cycles via /gamerule doDaylightCycle true/false.

Therefore this issue will be closed.
