### ISSUE TITLE
Server crashing on construction

### ISSUE THREAD

**Issue by eyemotif** [MC-U-Team/U-Team-Core#14]
When I start my server with uteamcore 2.0.0.81, it crashes with this reason:

`net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: info.u_team.u_team_core.intern.config.ClientConfig`

I'm running usefulbackpacks 1.3.0.9 (it never gets constructed because of the error).
I unzipped the file and I _think_ I found the file it's referring to, but I redownloaded the core file and it still crashes with the same reason.

**Comment by HyCraftHD** [comment]
Thank you very much for reporting this, as i didnt tested it on the server. Theres a hotfix on the way, so in the next release it should work. (Need curseforge approval, so could take some time)

**Comment by HyCraftHD** [comment]
https://minecraft.curseforge.com/projects/u-team-core/files/2621684
