### ISSUE TITLE
[1.12.2] Game freezes while starting the game

### ISSUE THREAD

**Issue by Axodique** [MC-U-Team/U-Team-Core#155]
### Bug description and reproduction steps

Unknown; happens at startup. Happens even if it is the only mod in the folder.

### Log files and Screenshots

![image](https://user-images.githubusercontent.com/49350272/147417801-52efbe7b-4104-4708-b6ae-2f6faef6db92.png)

here's the log : https://pastebin.com/G38PSjNv

### Used minecraft version

1.12.x

### Used forge version

14.23.5.2860

### Used mod version

u_team_core-1.12.2-2.2.5.147

**Comment by HyCraftHD** [comment]
Can you try to disable the discordRichPresence in the config file?

**Comment by Axodique** [comment]
That... actually worked. huh. I didn't try it because I thought discord rich presence wouldn't matter much, the more you know. Thank you a lot, haha.

**Comment by HyCraftHD** [comment]
Glad it helped. Yes there is unfortunately a bug in 1.12.2 where the discord rich presence timeout is broken. Need to fix that eventually 👍
