### ISSUE TITLE
[1.18.1] Crash on startup  "...net.minecraft.world.item.CreativeModeTab"

### ISSUE THREAD

**Issue by piousminion** [MC-U-Team/U-Team-Core#174]
### Bug description and reproduction steps

Crashes on server start.
The only other mod I have installed is a backpack mod, but I think the problem is here.
Please correct me if wrong.

Note: The minecraft version drop-down selector does not include 1.18 versions.

The Gist: 

> [23:42:00] [modloading-worker-0/INFO]: Mod uteamcore is signed with a valid certificate.
> [23:42:01] [main/ERROR]: Exception caught during firing event: 'net.minecraft.world.item.Item$Properties net.minecraft.world.item.Item$Properties.tab(net.minecraft.world.item.CreativeModeTab)'
> 	Index: 1
> 	Listeners:
> 		0: NORMAL
> 		1: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@159d79bd handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
> 		2: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@791112 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
> 		3: net.minecraftforge.eventbus.EventBus$$Lambda$3875/0x0000000801536160@160ecb8f
> 		4: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@5d493e42 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
> 		5: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@7bf7cd8c handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
> 		6: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@6afcfa48 handleEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)V
> java.lang.NoSuchMethodError: 'net.minecraft.world.item.Item$Properties net.minecraft.world.item.Item$Properties.tab(net.minecraft.world.item.CreativeModeTab)'
> 

### Log files and Screenshots

Latest Log:  [http://ix.io/3Ny9](http://ix.io/3Ny9)
Crashlog:  [http://ix.io/3Nya](http://ix.io/3Nya)

### Used minecraft version

1.17.x

### Used forge version

39.0.59

### Used mod version

1.18.1-4.0.0.201-SNAPSHOT

**Comment by HyCraftHD** [comment]
Please use the -non dev variant
