### ISSUE TITLE
crash report (version 2.2.4.107)

### ISSUE THREAD

**Issue by xXKILLER98Xx** [MC-U-Team/U-Team-Core#18]
Hello I have a problem with the u_team_core and is that i crash the game, any fixes?
[crash-2019-06-15_16.40.43-client.txt](https://github.com/MC-U-Team/U-Team-Core/files/3293481/crash-2019-06-15_16.40.43-client.txt)

**Comment by HyCraftHD** [comment]
This is an issue with the music player mod. Please reopen there. What other mods do you have installed?

**Comment by xXKILLER98Xx** [comment]
Yes, you were right was a problem with the music player. How do I solve the problem with the music player? will I have to go to the music player forum?

**Comment by HyCraftHD** [comment]
Here: https://github.com/MC-U-Team/Music-Player
The problem is an other mod causing issues with the music player mod.

**Comment by xXKILLER98Xx** [comment]
I don't see a solution there. Do I have to do the same thing I did here but there?

**Comment by HyCraftHD** [comment]
Just open an issue there with all information. This bug is unknown yet.

**Comment by xXKILLER98Xx** [comment]
ok
