### ISSUE TITLE
[MC-Version] 1.12.2

### ISSUE THREAD

**Issue by ILove07Gold** [MC-U-Team/U-Team-Core#201]
### Bug description and reproduction steps

disable discord rich feature in the config to disabled/off by default. it was one and stopping me from running modpack, looks like tons of other people had to same problem. Just keep it off. Just keep it off by default. 

### Log files and Screenshots

dsfsdfds

### Used minecraft version

1.12.x

### Used forge version

dsfsdfsd

### Used mod version

sdfsdfsdf

**Comment by HyCraftHD** [comment]
That's already implemented in the latest 1.12.2, 1.14.4, 1.15.2, 1.16.5 and 1.18.2 versions.
Maybe you need to delete the old config file to take effect.
