### ISSUE TITLE
[MC-Version] 1.15.2

### ISSUE THREAD

**Issue by DBTwenty5** [MC-U-Team/U-Team-Core#202]
### Bug description and reproduction steps

When launching 1.15.2 with UTeam Core, the came crashes and gives me this error code in the launcher: 
Error: java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank

I am using all of the mods from the modpack QTech, Enhnced Spawners, Optifine, Glasscutter, and Useful Railroads which requires UTeam Core.

### Log files and Screenshots

![Screenshot 2022-04-26 063412](https://user-images.githubusercontent.com/104429913/165281602-15612690-9edb-445b-aea4-817f66b4273f.png)
![Screenshot 2022-04-26 063435](https://user-images.githubusercontent.com/104429913/165281637-420ded17-deeb-4226-81a0-ae39eb750acb.png)
![Screenshot 2022-04-26 063544](https://user-images.githubusercontent.com/104429913/165282087-629bcca6-9ae0-4b92-8db5-642f8ee69086.png)

### Used minecraft version

1.15.x

### Used forge version

31.2.31

### Used mod version

3.0.2.169

**Comment by HyCraftHD** [comment]
The screenshot indicates an error with mekanism. But to get further information please upload the log file and the crashlog file here

**Comment by DBTwenty5** [comment]
Here is the crashlog file. I wasnt able to find the log file.
[crash-2022-04-26_18.45.03-client.txt](https://github.com/MC-U-Team/U-Team-Core/files/8567347/crash-2022-04-26_18.45.03-client.txt)

**Comment by HyCraftHD** [comment]
Thats an issue with mekanism and not utemacore
