### ISSUE TITLE
1.18.2 Crash when opening MP3 Menu

### ISSUE THREAD

**Issue by RetroGamerAndre** [MC-U-Team/U-Team-Core#205]
Whenever I hit F8 the game crashes. Crashlog references a keypressed event handler
[crash-2022-05-29_15.49.00-client.txt](https://github.com/MC-U-Team/U-Team-Core/files/8794304/crash-2022-05-29_15.49.00-client.txt)
. Any help would be greatly appreciated, the mp3 player mod is one of my favorite mods to use and not being able to access the menu and listen to my music is a little sad. Thanks for your time!

RetroGamerAndre

**Comment by HyCraftHD** [comment]
Thanks for the report. Should be fixed in this musicplayer version: https://www.curseforge.com/minecraft/mc-mods/music-player/files/3810230
