### ISSUE TITLE
[1.19] Crash

### ISSUE THREAD

**Issue by HICMGUN** [MC-U-Team/U-Team-Core#207]
### Bug description and reproduction steps

Bug causes crash on start up of the game. This mod along with USEFUL BACKPACKS and AQUACULTURE2 are causing this bug.

### Log files and Screenshots

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1

[crash-2022-07-08_22.45.21-client.txt](https://github.com/MC-U-Team/U-Team-Core/files/9075748/crash-2022-07-08_22.45.21-client.txt)

### Used minecraft version

1.19.x

### Used forge version

41.0.38

### Used mod version

1.19

**Comment by HyCraftHD** [comment]
Can you attach the debug log file please?

**Comment by dorktripp** [comment]
Hello, I'm also experiencing such issues with the new forge version also. Here's my debug log file. I'm certain it's similar.

Both useful backpacks, and u team core were working on forge 1.19-41.0.63, but not on version 1.19-41.0.98

[latestuteamcoredebuglog.txt](https://github.com/MC-U-Team/U-Team-Core/files/9097462/latestuteamcoredebuglog.txt)

**Comment by HyCraftHD** [comment]
Fixed with the latest versions: https://www.curseforge.com/minecraft/mc-mods/u-team-core/files/3875625
