### ISSUE TITLE
Music Player Mod isn't working

### ISSUE THREAD

**Issue by leugim23** [MC-U-Team/U-Team-Core#22]
I'm playing on 1.11.2 and when I type a song to get into the queue it says "Added to the queue!" And then it disappears from the queue, if I quickly press pause or repeat it stays there until I click play or disaple repeat.

**Comment by HyCraftHD** [comment]
Hello,
1.11 is not supported anymore. Please use a minecraft version where there is a 2.0.x version of musicplayer available.
~Johannes
________________________________
