### ISSUE TITLE
[1.19.3]  Not compatible with 1.19.3

### ISSUE THREAD

**Issue by vandon1** [MC-U-Team/U-Team-Core#220]
### Bug description and reproduction steps

Load mod into proper directory
Start 1.19.3
Crash

### Log files and Screenshots

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Music Player' (musicplayer) 2.4.1.11 with any version that is compatible with:
		 - uteamcore, any version
		 - minecraft 1.19.3
	 - Replace mod 'U Team Core' (uteamcore) 4.1.0.8 with any version that is compatible with:
		 - minecraft 1.19.3
Unmet dependency listing:
	 - Mod 'Music Player' (musicplayer) 2.4.1.11 requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'U Team Core' (uteamcore) 4.1.0.8 requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Used minecraft version

1.19.x

### Used forge version

fabric 0.14.11

### Used mod version

4.1.0.8

**Comment by HyCraftHD** [comment]
Is updated to 1.19.3 by now
