### ISSUE TITLE
[1.14.4] Forge Version Incompatability

### ISSUE THREAD

**Issue by Morpheus1101** [MC-U-Team/U-Team-Core#23]
Im running Forge 28.0.9 however the mod dosent like it and is requiring 28.0.27 or higher, which obviously im using.

**Comment by HyCraftHD** [comment]
28.0.9 < 28.0.27 so its working correctly.
You need a forge version later or equal than 28.0.27.

**Comment by Morpheus1101** [comment]
Arg, apologies, stupid Curse client...i though 28.0.9 was 28.0.90 .. i will remedy this which will solve all my issues

**Comment by HyCraftHD** [comment]
No problem :D
