### ISSUE TITLE
[1.14.4] Forge version incompatibility.

### ISSUE THREAD

**Issue by FuuNoKamiOka** [MC-U-Team/U-Team-Core#25]
I see that someone had this issue before, but I figured I'd make a new one.

I'm running Forge 28.1.8 and I am getting an error saying that the backpacks mod needs "28.1.20" or higher. I think something went wrong on your end because that's borked.

![image](https://user-images.githubusercontent.com/9029427/66006649-5b944780-e47d-11e9-965b-aaadc488a62c.png)

**Comment by HyCraftHD** [comment]
You need a recent forge version. The list states that your forge version is 28.1.8, but uteamcore requires at least 28.1.11 and usefulbackpacks at least 28.1.20.
You need a newer forge version than 28.1.20.

The latest forge version currently is 28.1.26

**Comment by FuuNoKamiOka** [comment]
...
Twitch client needs to change their things. This is REALLY confusing.
![image](https://user-images.githubusercontent.com/9029427/66007106-fe999100-e47e-11e9-8033-f6e6f4a21b95.png)

**Comment by HyCraftHD** [comment]
I know, the order is very very dumb. This is why it often happens.
Hopefully it works for you now!

**Comment by FuuNoKamiOka** [comment]
I just tried it and it did indeed work. I apologize for making this. lol

**Comment by HyCraftHD** [comment]
👍 
I'll close this now. Feel free to reopen if any other issues occur.
