### ISSUE TITLE
needs javafml:30

### ISSUE THREAD

**Issue by oscarOwOx** [MC-U-Team/U-Team-Core#28]
I tbh don't realy know a lot about the ind eph of mods so I don't how to fix it needing javafml:30

**Comment by HyCraftHD** [comment]
Please fill the whole bug issue template. With these information I cannot help you.
It seems you have installed a forge version older than 1.15.1 but you are trying to use the mod that requires 1.15.1 forge.

**Comment by HyCraftHD** [comment]
As there is no response I close this issue. Please reopen with the issue still apears.
