### ISSUE TITLE
conflict with the mod Ruins

### ISSUE THREAD

**Issue by phiphila** [MC-U-Team/U-Team-Core#29]
When start minecraft (Forge 14....109) with mods: Ruins ruins-1.14.4.4,  and u_team_core-1.14.4-2.8.0.139  then the chests in Ruins are empty
is I run minecraft just with Ruins ruins-1.14.4.4 all is ok.

Steps to reproduce:

run minecraft with these mods
find a Ruins chest and open a chest
it is empty
What I expected to happen:

What happened instead:

**Comment by HyCraftHD** [comment]
Please use the issue template ...
Also I need more information about what exactly you tried and which other mods your use. Also what mod is ruins. Please link that mod.

**Comment by phiphila** [comment]
you can find ruins here:
https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system

I did several tests, deleting the installed mods (about twenty) step by step, one after the other, to find the one that was in conflict with Ruins, because in this mods the chests generated was empty. so, I ended up finding that U-Team-Core was in conflict with ruins, so I deleted all the mods, then start minecraft just with ruins, the chests (generated in the structures created by the ruins mod) are full, then replaced just U-Team-Core and ruins and restarted minecraft, the chests are then empty (the newly generated chests).
A strange thing, this conflict is only present from my minecraft server, in "local" (a solo game) there is no conflict ....
I play with minecraft in 1.14.4

**Comment by HyCraftHD** [comment]
I've tested it with the latest version of both mods on 1.14.4 and cannot reproduce. I'll close for now. Please reopen if the issue still persists.
