### ISSUE TITLE
[MC-Version] 1.20.1

### ISSUE THREAD

**Issue by Scorpions95** [MC-U-Team/U-Team-Core#329]
### Bug description and reproduction steps

N/A
Is there U team core for minecraft version 1.20.1 ?

### Log files and Screenshots

![Screenshot 2023-08-12 18 20 52](https://github.com/MC-U-Team/U-Team-Core/assets/24534657/f76db747-9163-4067-9f69-528ebf4c3ced)

### Used minecraft version

1.20.x

### Used forge or fabric version

Forge 47.1.3

### Used mod version

5.1.4.269

**Comment by HyCraftHD** [comment]
Yes, https://www.curseforge.com/minecraft/mc-mods/u-team-core/files/4681290
