### ISSUE TITLE
[Fabric + Velocity] U-Team-Core Cannot verify version over a proxy

### ISSUE THREAD

**Issue by Neubulae** [MC-U-Team/U-Team-Core#330]
### Detailed description of the feature

Connecting to a server behind a proxy causes the version check to fail.

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by femboyfin** [comment]
Any update on this?

**Comment by Neubulae** [comment]
No, I decided to get around this by overriding version number but then packet issues arose, U Team Core specifically expected a proper information exchange between server and client and proxies mess that up
