### ISSUE TITLE
Upload 1.18.2 version on modrinth

### ISSUE THREAD

**Issue by Fefedu973** [MC-U-Team/U-Team-Core#342]
### Detailed description of the feature

Upload 1.18.2 version on modrinth

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
New versions of uteamcore are available on modrinth. Older versions may become available in the future.
https://modrinth.com/mod/u-team-core
