### ISSUE TITLE
[1.14.4] Can't load this mod at all

### ISSUE THREAD

**Issue by McFireWolf** [MC-U-Team/U-Team-Core#35]
**Describe the bug**
I tried to download and use the Useful Backpacks mod, so I downloaded UTeam Core since that's what's required. The game always crashes while the mods are being constructed. I removed the Useful Backpacks mod from the folder with my mods, and with only UTeam Core, the game still crashes. Is there a fix for this? I've tried to redownload it, and I'm on the newest forge version for 1.14.4

**To Reproduce**
1. Download UTeam Core for 1.14.4 (most recent file)
2. Place mod in the mods folder
3. Start Minecraft
4. Game ends up crashing (for me)

**Expected behavior**
You should load up the game, have it go through th eprocess until it launches 1.14.4, and when it's loading all the mods it will crash.

**Screenshots**
![Screenshot (16)](https://user-images.githubusercontent.com/61443684/75213319-f2241680-5746-11ea-8e62-8e573dab602f.png)
![Screenshot (17)](https://user-images.githubusercontent.com/61443684/75213324-f6503400-5746-11ea-86ce-08ffc326317f.png)
![Screenshot (18)](https://user-images.githubusercontent.com/61443684/75213332-fc461500-5746-11ea-9f9a-c034f66e6864.png)

**Versions**
- Minecraft version: 1.14.4
- Forge version: 28.2.1
- UTeamCore version: 2.8.2.150

**Log (if crash occures)**
[crash-2020-02-24_20.41.50-client.txt](https://github.com/MC-U-Team/U-Team-Core/files/4247986/crash-2020-02-24_20.41.50-client.txt)

**Comment by HyCraftHD** [comment]
Seems like a config problem. Please delete the config folder and try again.

**Comment by McFireWolf** [comment]
how do I redownload the config file?

**Comment by McFireWolf** [comment]
*folder

**Comment by HyCraftHD** [comment]
You don't. It is created on startup but seems to be corrupted. (This is a forge bug and not an issue on this mod specifically)
Just delete the config folder and it should work

**Comment by McFireWolf** [comment]
Thank you so much! It worked. I will keep this in mind if the issue comes up again. Glad to have helpful folks like you in this community!

**Comment by HyCraftHD** [comment]
Glad it worked!
Thanks for the kind words!
