### ISSUE TITLE
[1.15.2-forge-31.1.44] Mod conflict with enchantmentcontrol-1.2

### ISSUE THREAD

**Issue by Artellia** [MC-U-Team/U-Team-Core#37]
Error loading mods: U Team Core encountered an error during the load_registeries event phase.
An unexpected critical error was encountered.

**To Reproduce**
1. Clean install [1.15.2-forge-31.1.44]
2. Add the following to the mods folder:
u_team_core-1.15.2-2.11.0.156
extratags-1.0
MixinBootstrap-1.0.1
enchantmentcontrol-1.2

*Note: extra tags and mixinbootstrap are dependencies of enchantment control but do not cause the load error on their own.

**Expected behavior**
A successful load to the menu screen.

**Screenshots**
n/a

**Versions**
- Minecraft version: 1.15.2
- Forge version: 31.1.44
- UTeamCore version: 2.11.0.156

**Log (if a crash occurs)**
No crash log generated.

**Comment by HyCraftHD** [comment]
Please attach the whole log

**Comment by Artellia** [comment]
it did not create a log. the mod failed to load but there was no crash.

**Comment by HyCraftHD** [comment]
There is a log under logs/latest.log or logs/debug.log

**Comment by Artellia** [comment]
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/4472675/latest.log)

Thanks for pointing that out. I found it.

**Comment by HyCraftHD** [comment]
Thats a bug on enchantment controls mixin: 
```java
[13Apr2020 20:48:51.635] [Render thread/FATAL] [mixin/]: Mixin apply failed enchantmentcontrol.mixins.json:EnchantRandomlyMixin -> net.minecraft.world.storage.loot.functions.EnchantRandomly: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field enchantments was not located in the target class net.minecraft.world.storage.loot.functions.EnchantRandomly. Using refmap enchantmentcontrol.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field enchantments was not located in the target class net.minecraft.world.storage.loot.functions.EnchantRandomly. Using refmap enchantmentcontrol.refmap.json
```

**Comment by HyCraftHD** [comment]
I've reported it to enchantment control: https://github.com/Tfarcenim/EnchantmentControl/issues/2

**Comment by HyCraftHD** [comment]
Issue closed in Enchantment Control. Close it here aswell
