### ISSUE TITLE
[1.20.1] Is there any way to make this compatible with neoforge again?

### ISSUE THREAD

**Issue by Zedrimar** [MC-U-Team/U-Team-Core#391]
### Detailed description of the feature

Forge version bump made this mod no longer compatible with neoforge. Is there any chance to make it compatible with neoforge again? Not sure if it's possible with any back end changes that may have been made, but wanted to ask anyway.

Version of the core mod in question: 5.1.4.280

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
#392

Should be fixed with version [5.1.4.289](https://legacy.curseforge.com/minecraft/mc-mods/u-team-core/files/5220179)

**Comment by Zedrimar** [comment]
Awesome, thank you! :D
