### ISSUE TITLE
[MC-Version] 1.20.1 Neoforge support broken with new version

### ISSUE THREAD

**Issue by mxnmnm** [MC-U-Team/U-Team-Core#392]
### Bug description and reproduction steps

The version restrictions on the new update make it so that the mod does not work with neoforge. You need to change the forge requirement versions to match with the ones neoforge uses.

### Log files and Screenshots

https://gist.github.com/mxnmnm/904001f65d5064731123dcdd8b9bcdab

### Used minecraft version

1.20.x

### Used forge or fabric version

Neoforge 47.1.101

### Used mod version

5.1.4.280

**Comment by HyCraftHD** [comment]
Should be fixed with version [5.1.4.289](https://legacy.curseforge.com/minecraft/mc-mods/u-team-core/files/5220179)
