### ISSUE TITLE
[1.20.4 NeoForge] Can't enter on server without installing this mod on server side, even if this mod used only for Music Player

### ISSUE THREAD

**Issue by Fl414r** [MC-U-Team/U-Team-Core#395]
### Bug description and reproduction steps

1) Install any NeoForge modpack (FTB Neotech in my case)
2) Add U Team Core (and Music Player)
3) Try to enter on any server that hosts this modpack... fail

### Log files and Screenshots

![2024-06-17_08 16 48](https://github.com/MC-U-Team/U-Team-Core/assets/74704475/ff318b6d-c4d5-4b0e-9f01-67439f9c4bcb)

### Used minecraft version

1.20.x

### Used forge or fabric version

NeoForge 20.4.237

### Used mod version

5.3.0.300

**Comment by HyCraftHD** [comment]
Thanks, fixed in the latest versions
