### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by judicius** [MC-U-Team/U-Team-Core#40]
Mod uteamcore requires forge 31.2.20 or above. Currently, forge is 31.2.9

**To Reproduce**
updgrade to release 2.12.1.158 on forge 31.2.9

**Expected behavior**

**Screenshots**
![uteam](https://user-images.githubusercontent.com/30104638/85228159-c55bd500-b3af-11ea-81b6-8328470f17bc.PNG)

**Versions**
- Minecraft version: 1.15.2
- Forge version: 3.2.9
- UTeamCore version: 1.15.2-2.12.1.158

**Comment by HyCraftHD** [comment]
You therefore need to update to forge 31.2.20.
I don't see a problem here

**Comment by judicius** [comment]
I think the problem is I shouldn't report bugs before drinking a second cup of coffee. I was reading 31.2.20 as 31.2.2.0 therefore less than 3.2.9
