### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by jigaming** [MC-U-Team/U-Team-Core#42]
**starts to go and crashes**

**i have the useful_backpacks-1.14.4-1.7.6.60.jar and u_team_core-1.14.4-2.8.2.150-dev.jar**
Steps to reproduce the behaviour:
1. Go to 'play'
2. and it will load but crash just before the logo pops up

i have tried about 15 times and even deleted the config but can figure out whats wrong

**Screenshots**
![mc crash](https://user-images.githubusercontent.com/68482253/87861764-217b3000-c941-11ea-98b3-9c7ef76c6c4a.PNG)

**Versions**
- Minecraft version: 1.14.4
- Forge version: 1.14.4-forge-28.2.0
- UTeamCore version: 1.14.4-2.8.2.150

[crash-2020-07-18_21.44.12-client.txt](https://github.com/MC-U-Team/U-Team-Core/files/4942495/crash-2020-07-18_21.44.12-client.txt)

**Comment by HyCraftHD** [comment]
You downloaded the dev version: 
![grafik](https://user-images.githubusercontent.com/7681220/87861842-7a02fb00-c94a-11ea-9e01-49675166e756.png)
You need the normal version for the normal run
