### ISSUE TITLE
[1.15.2] Config being ignored / Missing Config Statements?

### ISSUE THREAD

**Issue by CDAGaming** [MC-U-Team/U-Team-Core#44]
**Describe the bug**
I'm the owner of the mod CraftPresence, a discord rich presence mod for MC b1.6.6 - 1.16.2-Pre1.

While testing in correspondence with https://gitlab.com/CDAGaming/CraftPresence/-/issues/60 I noticed this piece of info:

```
[m[32m[05:24:56] [Discord Rich Presence Stop Thread/INFO] [UTeamCore/]: Discord client closed.
[m[32m[05:24:56] [CraftPresence-ShutDown-Handler/INFO] [craftpresence/]: Shutting Down CraftPresence...
```

However, this is the config for your mod:

```
#Client configuration settings
[client]
	#If you have discord installed it will show your some details about your game as rich presence
	discordRichPresence = false
```

This is leading me to question as to whether this config option is being employed properly, and if not, if it could be employed to prevent a possible conflict between our mods Discord implementations.

**To Reproduce**
1. Just Launching is all this needs, default setup of the pack explained in the aforementioned issue page.

**Expected behavior**
Explained in Description.

**Screenshots**
N/A, test screenshots in aforementioned gitlab issue page.

**Versions**
- Minecraft version: 1.15.2
- Forge version: 31.2.36
- UTeamCore version: 3.0.1.164

**Log (For reference)**
https://paste.ee/p/SSvfH

**Comment by HyCraftHD** [comment]
Hello. This message will always be printed out even if the config is disabled. I might rework this soon (1.16+), so the shutdown hook only prints the message if the client was connected.

Either way the config value should still prevent the client from connecting so I don't think that it causes an issue with your mod.
https://github.com/MC-U-Team/U-Team-Core/blob/569559d83fa06ae72b55beef04d6aab20442fa07/src/main/java/info/u_team/u_team_core/intern/proxy/ClientProxy.java#L18-L20

https://github.com/MC-U-Team/U-Team-Core/blob/569559d83fa06ae72b55beef04d6aab20442fa07/src/main/java/info/u_team/u_team_core/intern/discord/DiscordRichPresence.java#L30-L63

**Comment by CDAGaming** [comment]
Thank you for the explanation, I look forward to those changes!

**Comment by HyCraftHD** [comment]
In 1.16 this should now be addressed. The ``Discord client closed.`` should now only log if the connection was established before.
Hopefully that avoids confusion.
