### ISSUE TITLE
Crashing when initializing

### ISSUE THREAD

**Issue by Gh0st116** [MC-U-Team/U-Team-Core#46]
When I try to run the game it instantly crashes, giving an error, I tried running without the backpacks mod and it still gives the same error. Also I tried deleting the config folder, didn't went well either

Crash report:
https://pastebin.com/Tt2dxsvL

**Comment by HyCraftHD** [comment]
This crash seems to have nothing todo with uteamcore or useful backpacks. Try to remove optifine as this causes many issues with forge.

If that does not help, can you please attach the whole debug.log file?

**Comment by Gh0st116** [comment]
Oh, sorry then. It didn't help and I tried running the game with only uteamcore and useful backpacks on the mods folder, which didn't work too.
here's the debug of it: 
https://pastebin.com/VNykaa1Z 
thanks anyways ^^

**Comment by HyCraftHD** [comment]
Useful-Backpacks requires a forge version above yours: 
_Mod usefulbackpacks requires forge 33.0.37 or above §7Currently, forge is 33.0.34_

You need to update your forge to 33.0.37
