### ISSUE TITLE
Game Crashing During Initialization

### ISSUE THREAD

**Issue by Kmtseattle** [MC-U-Team/U-Team-Core#47]
Once I downloaded U-Team-Core for the Useful Backpacks addon, my game would not completely load, and it would crash.

The crash takes me back to the Minecraft Launcher, as most/all crashes do, but this one gave me an error saying:

"The game crashes whilst initializing game
Error: java.land.BootstrapMethodError:
java.lang.NoClassDefFoundError:
net/minecraft/world/IEnviromentBlockReader"

Please note that minutes earlier, I was playing just fine with all sorts of mods. 
Thanks, KKRadar.

**Comment by HyCraftHD** [comment]
The issue template is there for a reason. Fill that out to receive support
