### ISSUE TITLE
[1.16.3] Server Crash during startup

### ISSUE THREAD

**Issue by NielsPilgaard** [MC-U-Team/U-Team-Core#48]
**Describe the bug**
Servers with UTeamCore crash on startup.

**To Reproduce**
1. Setup a server with UTeamCore
2. Run it

**Expected behavior**
For the game to start

**Versions**
- Minecraft version: 1.16.3
- Forge version: 1.16.3-34.1.42
- UTeamCore version: 1.16.3-3.1.11.184

**Log (if crash occures)**
https://gist.github.com/NillerMedDild/4df1041c4509961788eb87f28cbd30fb

**Comment by HyCraftHD** [comment]
Should be fixed in this version: 
![image](https://user-images.githubusercontent.com/7681220/98179135-67fb9700-1efe-11eb-92ec-22f3ae55e096.png)

**Comment by NielsPilgaard** [comment]
Thanks for the swift fix :)
