### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by epicyeeto** [MC-U-Team/U-Team-Core#49]
uteamcore version: u_team_core-1.12.2-2.2.5.147.jar
forge: forge-14.23.5.2854
Minecraft: 1.12.2

so when I try to load in my mod pack it just does not load in it just crashes the log almost says nothing and idk the issue

crash log:
[2020-10-29-2.log.gz](https://github.com/MC-U-Team/U-Team-Core/files/5550400/2020-10-29-2.log.gz)

EDIT:
I went to my latest log and I came up with something else
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/5550611/latest.log)

**Comment by HyCraftHD** [comment]
Nothing in this log is a crash or indicates something is wrong with uteamcore.
The only thing I see is that you try to connect to a server but you are missing many mods
