### ISSUE TITLE
[1.12.2 Forge] Freeze and crash during compile

### ISSUE THREAD

**Issue by juyoen** [MC-U-Team/U-Team-Core#50]
**Describe the bug**
I start Minecraft with my 1.12.2 Forge installation and mods. As soon as the compile gets to U Team Core, it freezes and crashes. I can't get past this.

**To Reproduce**
1. Open Minecraft
2. Wait until "Compile mods" reaches U Team Core
3. Wait for Minecraft to freeze and crash

**Expected behavior**
Be able to play Minecraft with mods.

**Versions**
- Minecraft version: 1.12.2
- Forge version: 1.12.2-forge-14.23.5.2854
- UTeamCore version: u_team_core-1.12.2-2.2.5.147

**Log (if crash occures)**
Can't find one

**Comment by HyCraftHD** [comment]
If there is no log i cannot help you. Please send the the debug.log or latest.log from ```your minecraft installation/logs/debug.log``` or  ```your minecraft installation/logs/latest.log```

**Comment by HyCraftHD** [comment]
Closed because no response
