### ISSUE TITLE
[1.16.3] crashes on startup

### ISSUE THREAD

**Issue by Jarrod9991** [MC-U-Team/U-Team-Core#55]
**Describe the bug**
I downloaded U team core and useful railroads, when i open minecraft, it crshes saying "Mod File u_team_core-1.16.4-3.1.17.191.jar needs language provider javafml:35 or above to load"

**To Reproduce**
1. Open minecraft

**Expected behavior**
I expected minecraft to not crash

**Screenshots**

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.33
- UTeamCore version: 3.1.17.191

**Log (if crash occures)**
Link to crash log
[crash-2021-01-11_19.17.10-fml.txt](https://github.com/MC-U-Team/U-Team-Core/files/5794603/crash-2021-01-11_19.17.10-fml.txt)

**Comment by HyCraftHD** [comment]
The file and the tags on curseforge clearly indicate that this version if for minecraft version 1.16.4 and not 1.16.3. Please use the right versions.
