### ISSUE TITLE
[MC-Version] Error while loading MC

### ISSUE THREAD

**Issue by celtkr** [MC-U-Team/U-Team-Core#56]
**Describe the bug**
While loading with MC with _uteamcore_, an error occurred. The message read: "The mod uteamcore requires forge 35.1.13 or above. Currently, forge is 35.1.4"

Note: the same thing occurred when loading uteamcore version 1.16.4-3.1.16.190 as well

**To Reproduce**
1. Adding the uteamcore file into "...\.minecraft\mods"
2. Loading MC forge
3. Error message appear during the load

**Expected behavior**
MC was expected to load without issue since it was assumed to be compatible

**Screenshots**
![image](https://user-images.githubusercontent.com/77326026/104297171-803ef200-54fd-11eb-86f8-50b1488f5255.png)

**Versions**
- Minecraft version: 1.16.4
- Forge version: 1.16.4-35.1.4
- UTeamCore version: 1.16.4-3.1.17.191

**Log (if crash occures)**
[crash-2021-01-12_17.33.22-fml.txt](https://github.com/MC-U-Team/U-Team-Core/files/5801144/crash-2021-01-12_17.33.22-fml.txt)

**Comment by HyCraftHD** [comment]
No forge is currently at 35.1.36.
Please use the latest forge version, not the "recommended" one.
