### ISSUE TITLE
[MC-Version] Game crashed, there was a severe problem for the mod loading

### ISSUE THREAD

**Issue by ItzNoobex7u7** [MC-U-Team/U-Team-Core#64]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from U Team Core (uteamcore)
Código de error: -1

So i installed some mods for my minecraft and i thought it was something about forge or the mod version. but seems to be with the files i think

![Minecraft Error](https://user-images.githubusercontent.com/82043658/113730115-365d4680-96bd-11eb-8ab1-5b532994d772.png)

**Versions**
- Minecraft version: 1.12.2
- Forge version: 1.12.2 - 14.23.5.2854
- UTeamCore version: 1.12.2 - 2.2.4.107-dev

**Log (if crash occures)**
[crash-2021-04-06_09.40.47-client.txt](https://github.com/MC-U-Team/U-Team-Core/files/6265504/crash-2021-04-06_09.40.47-client.txt)

**Comment by HyCraftHD** [comment]
Do not use the -dev version. Use the normal one!
