### ISSUE TITLE
Crash - "(mod) error during load registries event"

### ISSUE THREAD

**Issue by Chrisjohnson57387** [MC-U-Team/U-Team-Core#65]
Hey, I'm getting the error in the title for all ucore mods right now. Just to be sure I made sure I wasn't using the "dev" version like some others' issues have, and I stripped down to just the U Core and still have the error. Full crash report below. I do have alot of other mods and can post the list if necessary. LMK if there's another mod you're certain causes conflict and I can remove it to test. Other thing to note! I was using useful backbacks , one of the 1.16.4 versions, and that was all working before updating to the U Core april 1st update.

I'm running 1.16.5
FML: 36.1

[crash-2021-04-15_16.10.16-fml.txt](https://github.com/MC-U-Team/U-Team-Core/files/6321636/crash-2021-04-15_16.10.16-fml.txt)

**Comment by HyCraftHD** [comment]
Please post the whole crashlog / debug.log as a file

**Comment by Chrisjohnson57387** [comment]
> Please post the whole crashlog / debug.log as a file

updated with file

**Comment by HyCraftHD** [comment]
Do you use curseforge as a download site?
Can you try it with this exact file: https://www.curseforge.com/minecraft/mc-mods/u-team-core/download/3257635

**Comment by Chrisjohnson57387** [comment]
I do use curse forge though I may have downloaded the wrong file, and had older versions of the others. I went through step and by step with fresh updates and installs and everything is working! Thank you for your time and sorry for the false alarm
