### ISSUE TITLE
Crashing With Optifine

### ISSUE THREAD

**Issue by CodWafer** [MC-U-Team/U-Team-Core#94]
I have the 1.8.9 version (To play hypixel with it) and I have Optifne_1.8.9_HD_U_M5 installed. This mod, when paired with optifine, causes minecraft to crash on startup.

**Comment by HyCraftHD** [comment]
1.8.9 is unsupported. Why do you need uteamcore for that version?
If you are using the musicplayer mod you can remove uteamcore for the 1.8.9 version

**Comment by CodWafer** [comment]
I am sorry, I just relised I put this in the wrong area, sorry
